//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopping.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductName { get; set; }
        public string productId { get; set; }
        public decimal productPrice { get; set; }
        public string productCategory { get; set; }
        public string productDescription { get; set; }
        public string productUrl { get; set; }
    }
}
